/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileBrowserDisplay_FileBrowserdisplay */

#ifndef _Included_FileBrowserDisplay_FileBrowserdisplay
#define _Included_FileBrowserDisplay_FileBrowserdisplay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileBrowserDisplay_FileBrowserdisplay
 * Method:    toFind
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_FileBrowserDisplay_FileBrowserdisplay_toFind
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
