/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BackupJNI_Restore_BackupJNI */

#ifndef _Included_BackupJNI_Restore_BackupJNI
#define _Included_BackupJNI_Restore_BackupJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BackupJNI_Restore_BackupJNI
 * Method:    toFind
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BackupJNI_1Restore_BackupJNI_toFind
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
