/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BackupJNI_Restore_Restorecopydata */

#ifndef _Included_BackupJNI_Restore_Restorecopydata
#define _Included_BackupJNI_Restore_Restorecopydata
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BackupJNI_Restore_Restorecopydata
 * Method:    restorecopydata
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BackupJNI_1Restore_Restorecopydata_restorecopydata
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
