/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BackupJNI_Restore_Backupcopydata */

#ifndef _Included_BackupJNI_Restore_Backupcopydata
#define _Included_BackupJNI_Restore_Backupcopydata
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BackupJNI_Restore_Backupcopydata
 * Method:    backupcopydata
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_BackupJNI_1Restore_Backupcopydata_backupcopydata
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
